name: "Pull Request Thank You"
description: "Post a comment to a Pull Request thanking the user for their submission"
inputs:
  GITHUB_TOKEN:
    description: "Github token of the repository (automatically created by Github)"
    required: true
runs:
  using: "node12"
  main: "index.js"
